# Generated by Django 4.2.5 on 2023-09-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='Edad',
            new_name='edad',
        ),
        migrations.AlterField(
            model_name='book',
            name='fechaDePublicacion',
            field=models.DateField(),
        ),
    ]
